#!/bin/sh

JAVA_OPTS='-Djava.awt.headless=true'

# Quote because path may contain spaces
if [ -h $0 ]
then
  ROOT_DIR="$(cd "$(dirname "$(readlink -n "$0")")" && pwd)"
else
  ROOT_DIR="$(cd "$(dirname $0)" && pwd)"
fi
cd "$ROOT_DIR"

CLASS_PATH="$ROOT_DIR/*:."

java $JAVA_OPTS -cp $CLASS_PATH scalive.client.AgentLoader $ROOT_DIR $@
